/**
 * GENERATED by scripts/pixelate/pixelate.py. Do not edit by hand; re-run the script.
 *
 * Native (logical-pixel) sizes of the site's pixel art in /public/assets/pixel. Every image is
 * shown only at integer multiples of these sizes with `image-rendering: pixelated`.
 * Sheets are horizontal strips of `frames` frames, each `frameW` x `frameH`, bottom-aligned;
 * `anchorX` is the column (from the frame's left edge) the feet are centred on.
 */

export interface SpriteSheetMeta {
  src: string;
  frameW: number;
  frameH: number;
  frames: number;
  /** Duration of one frame in ms (0 for a still). */
  frameMs: number;
  /** Feet centre, in native px from the left edge of a frame. */
  anchorX: number;
}

export interface PixelImageMeta {
  src: string;
  w: number;
  h: number;
}

export interface ForestMeta extends PixelImageMeta {
  /** Native row of the top of the grass ground line (0 = top row). */
  groundRow: number;
}

export type SheetPose = 'wave' | 'sit' | 'idle';

export const pixelSprites: {
  wave: SpriteSheetMeta;
  sit: SpriteSheetMeta;
  idle: SpriteSheetMeta;
  face: PixelImageMeta;
  forest: ForestMeta;
} = {
  wave: { src: '/assets/pixel/roy-wave.png', frameW: 41, frameH: 67, frames: 3, frameMs: 400, anchorX: 15 },
  sit: { src: '/assets/pixel/roy-sit.png', frameW: 36, frameH: 59, frames: 3, frameMs: 500, anchorX: 19 },
  idle: { src: '/assets/pixel/roy-idle.png', frameW: 28, frameH: 67, frames: 1, frameMs: 0, anchorX: 14 },
  face: { src: '/assets/pixel/roy-face.png', w: 38, h: 49 },
  forest: { src: '/assets/pixel/forest.png', w: 240, h: 112, groundRow: 101 },
};
