/**
 * GENERATED by scripts/pixelate/import_flow.py. Do not edit by hand; re-run the script.
 *
 * Native (one PNG pixel per art pixel) sizes of the Roy Runner sprites in
 * /public/assets/sprites. The game draws them 1:1 so the pixel grid stays crisp.
 */

export interface Size {
  readonly w: number;
  readonly h: number;
}

export const SPRITE_SIZES = {
  player: { w: 68, h: 92 },
  slide: { w: 68, h: 77 },
  obstacles: {
    racoon: { w: 66, h: 46 },
    stump: { w: 64, h: 58 },
    'stump-moss': { w: 66, h: 52 },
    rock: { w: 66, h: 53 },
    mushrooms: { w: 65, h: 63 },
    toadstools: { w: 65, h: 39 },
    agave: { w: 65, h: 51 },
    'bird-blue': { w: 63, h: 54 },
    'bird-brown': { w: 63, h: 46 },
    beetle: { w: 50, h: 37 },
    hedgehog: { w: 54, h: 43 },
    bat: { w: 58, h: 38 },
  },
  background: { w: 344, h: 192, groundRow: 162 },
  portrait: { w: 52, h: 56 },
} as const;
