/**
 * GENERATED by scripts/pixelate/import_flow.py. Do not edit by hand; re-run the script.
 *
 * Native (one PNG pixel per art pixel) sizes of the Roy Runner sprites in
 * /public/assets/sprites. The game draws them 1:1 so the pixel grid stays crisp.
 */

export interface Size {
  readonly w: number;
  readonly h: number;
}

export const SPRITE_SIZES = {
  player: { w: 68, h: 92 },
  slide: { w: 79, h: 75, top: 0 },
  slideMove: { w: 71, h: 88 },
  obstacles: {
    racoon: { w: 52, h: 36 },
    stump: { w: 57, h: 51 },
    'stump-moss': { w: 56, h: 45 },
    rock: { w: 51, h: 40 },
    mushrooms: { w: 38, h: 36 },
    toadstools: { w: 55, h: 33 },
    agave: { w: 66, h: 51 },
    'bird-blue': { w: 39, h: 34 },
    'bird-brown': { w: 46, h: 35 },
    beetle: { w: 45, h: 33 },
    hedgehog: { w: 42, h: 33 },
    bat: { w: 51, h: 34 },
  },
  background: { w: 344, h: 194, groundRow: 164 },
  portrait: { w: 52, h: 56 },
} as const;
